### ISSUE TITLE
Installation: ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by wyhinton** [3DSinghVFX/animation_nodes#186]
Getting the following error when installing [animation_nodes_v2_3_windows_py310.zip](https://github.com/3DSinghVFX/animation_nodes/releases/download/extranodes-cd-build/animation_nodes_v2_3_windows_py310.zip):

OS: Windows 10
Blender Version: 3.1.2

```
ImportError: numpy.core.multiarray failed to import
```

Full Error Message:
```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Primary User\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\animation_nodes\__init__.py", line 166, in <module>
    auto_load.init()
  File "C:\Users\Primary User\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\animation_nodes\auto_load.py", line 23, in init
    modules = get_all_submodules(Path(__file__).parent)
  File "C:\Users\Primary User\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\animation_nodes\auto_load.py", line 51, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
  File "C:\Users\Primary User\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\animation_nodes\auto_load.py", line 55, in iter_submodules
    yield importlib.import_module("." + name, package_name)
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "animation_nodes\algorithms\mesh_generation\find_shortest_path.pyx", line 1, in init animation_nodes.algorithms.mesh_generation.find_shortest_path
  File "C:\Users\Primary User\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\animation_nodes\data_structures\__init__.py", line 53, in <module>
    dataStructures = importDataStructures()
  File "C:\Users\Primary User\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\animation_nodes\data_structures\__init__.py", line 35, in importDataStructures
    from . sounds.sound import Sound
  File "C:\Users\Primary User\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\animation_nodes\data_structures\sounds\sound.py", line 4, in <module>
    from . sound_sequence import sampleRate
  File "C:\Users\Primary User\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\animation_nodes\data_structures\sounds\sound_sequence.py", line 3, in <module>
    import aud
ImportError: numpy.core.multiarray failed to import
```

**Comment by 3DSinghVFX** [comment]
@wyhinton Hi. Please remove the older version of AN, then fresh install the addon.

**Comment by LakshmiIC35134** [comment]
Getting the following error message while installing animation nodes and extra nodes. I also tried looking for animation_nodes folder in the \blender\3.1\scripts\addons subfolder but couldn't find it. 
OS: Ubuntu 20.04.4 LTS
Blender Version: 3.1.2

`Traceback (most recent call last):
  File "/home/hp/blender-3.1.2-linux-x64/3.1/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/hp/.config/blender/3.1/scripts/addons/animation_nodes/__init__.py", line 67, in <module>
    raise Exception(message)
Exception: 

There are multiple versions of the Animation Nodes addon installed.
Please uninstall/remove all older versions of the addon.

Animation Nodes has been found more than once in this folder:
  /home/hp/.config/blender/3.1/scripts/addons
`

**Comment by unity2k** [comment]
I know this a dumb place to leave this question but where is your version of AN for Python 3.10?

**Comment by 3DSinghVFX** [comment]
@unity2k Hi. All the builds are on the release page. AN+EN for Py10 : https://github.com/3DSinghVFX/animation_nodes/releases/tag/extranodes-cd-build
