### ISSUE TITLE
Animation Nodes 3d viewer in viewport not working in Blender 4.0.0

### ISSUE THREAD

**Issue by meikasahara** [3DSinghVFX/animation_nodes#188]
Animation nodes 3d viewer does not display graphics output in the 3d viewport in Blender 4.0.0. The following error appears in the console:

```
Traceback (most recent call last):
  File "/home/diffeomorphist/.config/blender/4.0/scripts/addons/animation_nodes/base_types/nodes/node_ui_extension.py", line 66, in drawNodeUIExtensions
    drawExtensionsForNode(node, extensions, position, width)
  File "/home/diffeomorphist/.config/blender/4.0/scripts/addons/animation_nodes/base_types/nodes/node_ui_extension.py", line 75, in drawExtensionsForNode
    height = extension.draw(node, position, width)
  File "/home/diffeomorphist/.config/blender/4.0/scripts/addons/animation_nodes/base_types/nodes/node_ui_extension.py", line 34, in draw
    textBox.draw()
  File "/home/diffeomorphist/.config/blender/4.0/scripts/addons/animation_nodes/graphics/text_box.py", line 29, in draw
    self.boundary.draw(
  File "/home/diffeomorphist/.config/blender/4.0/scripts/addons/animation_nodes/graphics/rectangle.py", line 71, in draw
    shader = gpu.shader.from_builtin('2D_UNIFORM_COLOR')
ValueError: expected a string in ('FLAT_COLOR', 'IMAGE', 'IMAGE_COLOR', 'SMOOTH_COLOR', 'UNIFORM_COLOR', 'POLYLINE_FLAT_COLOR', 'POLYLINE_SMOOTH_COLOR', 'POLYLINE_UNIFORM_COLOR'), got '2D_UNIFORM_COLOR'

```
Some changes to the 4.0.0 API must be causing this behavior.

**Comment by 3DSinghVFX** [comment]
Thanks for the report. We will look into this.

**Comment by meikasahara** [comment]
https://github.com/JacquesLucke/animation_nodes/commit/7697f9dfceeabc653755d545887c76f5af2e6bb7 
This commit fixes the issue but there are compiled versions of this available yet.
