### ISSUE TITLE
KeyError: 'Numpy Array'

### ISSUE THREAD

**Issue by IgorVe** [3DSinghVFX/animation_nodes#191]
Hey to all.
Downloaded a project of a Neural Network [here](https://github.com/barckley75/Blender_Neural_Network), installed proper versions of Blender (2.93.1) and Animation nodes (2.2.2), but there are some errors in the node tree....

location: <unknown location>:-1
Python: Traceback (most recent call last):
  File "C:\Users\111\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\animation_nodes\base_types\nodes\base_node.py", line 188, in draw_label
    return self.drawLabel()
  File "C:\Users\111\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\animation_nodes\nodes\list\create_list.py", line 56, in drawLabel
    return "Create " + toListDataType(self.assignedType)
  File "C:\Users\111\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\animation_nodes\sockets\info.py", line 138, in toListDataType
    return _socketInfo.listDataType[input]
KeyError: 'Numpy Array'

How it looks inside the Blender:
![Screenshot (78)](https://github.com/3DSinghVFX/animation_nodes/assets/156939200/8ee5b48e-809b-4325-a35d-a14425077717)

How to fix it? Thanx!

**Comment by 3DSinghVFX** [comment]
Hi.
Sorry for the late reply. I think you should install the Animation Nodes + Extra Nodes (Forked) build from this: https://github.com/3DSinghVFX/animation_nodes/releases
