### ISSUE TITLE
Exception in Blender 4.0, "mesh object input" node

### ISSUE THREAD

**Issue by indrajit-kanjilal** [3DSinghVFX/animation_nodes#192]
With a simple setup with "[animation_nodes_v2_3_windows_py310.zip](https://github.com/3DSinghVFX/animation_nodes/releases/download/extranodes-cd-build/animation_nodes_v2_3_windows_py310.zip)"
imported in Blender 4.0.2 , just viewing the Mesh output is generating a Exception in console:

Traceback (most recent call last):
  File "C:\Users\193899744\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\animation_nodes\execution\main_execution_unit.py", line 38, in executeUnit
    exec(self.executeCodeObject, self.executionData, self.executionData)
  File "execution: 'Animation Nodes'", line 13, in <module>
  File "C:\Users\193899744\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\animation_nodes\extend_bpy_types.py", line 109, in getBevelVertexWeights
    self.mesh.vertices.foreach_get("bevel_weight", bevelVertexWeights.asNumpyArray())
AttributeError: foreach_get(..) 'Mesh.                                                                                                                                                                                                vertices[...]' elements have no attribute 'bevel_weight'

![anim-node-issue](https://github.com/3DSinghVFX/animation_nodes/assets/43871864/06caf3da-567a-4228-ab39-30bf500c4bc7)
![anim-node-issue-console](https://github.com/3DSinghVFX/animation_nodes/assets/43871864/90b59723-3abf-408c-a3ad-4279c2308d8f)

**Comment by 3DSinghVFX** [comment]
Hi. Thanks for the report.
Have you checked with Blender 3.6?

**Comment by indrajit-kanjilal** [comment]
Works like a charm (the python 3.10 version "animation_nodes_v2_3_windows_py310.zip" for blender 3.6.8 LTS.

Only broken in 4.0

![anim-node-issue](https://github.com/3DSinghVFX/animation_nodes/assets/43871864/6b08dab6-97d0-447f-8928-3f6d004ad4db)

**Comment by 3DSinghVFX** [comment]
Okay, I'll look into that.

**Comment by indrajit-kanjilal** [comment]
Thanks,

    Here is the blender file I used in blender 3.6.8 LTS. with latest animation_nodes_v2_3_windows_py310.zip

[Animation-node-att-txr.zip](https://github.com/3DSinghVFX/animation_nodes/files/14011420/Animation-node-att-txr.zip)

**Comment by 3DSinghVFX** [comment]
Hi. I have updated the `extranodes` branch. Please try the latest build from the release.

**Comment by indrajit-kanjilal** [comment]
It is working, many thanks Kuldip
RegardsIndrajit
    On Sunday, 28 January, 2024 at 07:35:57 pm IST, Kuldeep Singh ***@***.***> wrote:  
 
 


Hi. I have updated the extranodes branch. Please try the latest build from the release.
